version: "3.9"

services:
  web:
    build: ./frontend
    volumes:
      - web_static:/usr/src/app/build

  web_api:
    build: ./backend
    networks:
      - backend

  proxy:
    image: nginx:alpine
    depends_on:
      - web_api
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web_static:/usr/share/nginx/html

networks:
  backend:

volumes:
  web_static:

